name: JaCoCo Report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and test with Maven
        run: mvn clean test

      - name: Generate JaCoCo Report
        run: mvn jacoco:report

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html
