name: Do a mvn clean install and SonarCloud analysis on push or merge request
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build with Maven and analyze with SonarCloud
        run: |
          mvn clean install
          mvn sonar:sonar \
            -Dsonar.organization=<your_SonarCloud_organization_key> \
            -Dsonar.projectKey=<your_project_key> \
            -Dsonar.sources=src/main/java,src/test/java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
